### ISSUE TITLE
Stop capturing during NVS access

### ISSUE THREAD

**Issue by chunter1** [chunter1/precipitationSensorESP32#11]
Since access to the NVS seems to interfere with the ADC sampling timer ISR, we should stop capturing during NVS access.

**Comment by hcs-svn** [comment]
That's already implemented.
See https://github.com/chunter1/precipitationSensorESP32/issues/9
But perhaps there may be a situation wherer it does not work?

**Comment by chunter1** [comment]
No, just didn't notice that it was already done.
