### ISSUE TITLE
bin number configuration

### ISSUE THREAD

**Issue by hcs-svn** [chunter1/precipitationSensorESP32#2]
"First and last bin-number for each bin-group (uint16 firstBin[32], uint16 lastBin[32])"

What shall get configured and how and where shall it be used?

**Comment by chunter1** [comment]
User shall be able to define firstBin and lastBin for each of the 32 binGroups.
Please have a look at the recent FHEM post :)

**Comment by hcs-svn** [comment]
OK. I will try to get the frontend working generally and then I will add this configuration

**Comment by hcs-svn** [comment]
Done
