### ISSUE TITLE
Strategy for FHEM communication

### ISSUE THREAD

**Issue by hcs-svn** [chunter1/precipitationSensorESP32#3]
Possibilities:
1) ) as is (use dummy in FHEM)
2) ) like LGW (firmware provides tcp-port and module works like 36_LaCrosseGateway)

Advantages: 
1) ) nothing else must get implemented

2) ) FHEM module can provide options (that can or should not be in the firmware) like
- OTA update
- calculations
- validations
- settings (like init commands in LGW)

**Comment by chunter1** [comment]
ad 1.) For development/debug i would keep that part of the code in parallel by now.
ad 2.) I personally prefere this version since it is the way FHEM users are used to and offers a clean presentation. However i have no experience in implementing such an module.

**Comment by hcs-svn** [comment]
OK, I guess the question is answered :-)
