### ISSUE TITLE
Limit bin-range in bin-group selection to 1...255

### ISSUE THREAD

**Issue by chunter1** [chunter1/precipitationSensorESP32#5]
Since bin0 denotes 0 Hz, and values greater than 255 are not allowed, we should add a check here or at least avoid writing such numbers to the NFS.

**Comment by hcs-svn** [comment]
I will remove bin 0 from the setup page

**Comment by hcs-svn** [comment]
And after reading once again what you wrote :-) I will also add a range check from 1 to 255

**Comment by hcs-svn** [comment]
What I will implement:
- Bin group 1 will get the default 1 ... 7 (instead of 0 ... 7)
- Save settings in the frontend validates if all bin numbers are in the range 1 ... 255
- Do not save the settings if the bin numbers are not valid
- Tell the user that the bin numbers are not valid

**Comment by chunter1** [comment]
Absolutely perfekt :)

**Comment by hcs-svn** [comment]
Done
