### ISSUE TITLE
Sensor mounting angle

### ISSUE THREAD

**Issue by chunter1** [chunter1/precipitationSensorESP32#7]
To allow evaluation of different sensor mounting angles, it would be great if we could add an "sensor mounting angle" field to the setup page. (and automaticall adapt the calculated speeds on the help page)
Where 0° = facing upward.
I could then dynamically adapt the FOV related parameters in the signal processing part.

**Comment by hcs-svn** [comment]
I will add a configuration row on the setup page:
`Mounting angle: [  45] degree (0 is facing upward)`

Default is 45
You can get the value (or the default of 45) using this call:
`settings.GetUInt("SMA", 45);`

Watch this issue for "done"

could you please provide the adapted formula for m/s ?
> float mps = ((freq * (0.3 / 24.15)) / 2.0) * sqrtf(2.0);

**Comment by chunter1** [comment]
Thanks!
Here is the formula:
`float mps = ((freq * (0.3 / 24.15)) / 2.0) / cos(angle);`

If angle is needed in radiant, then this version applies:
`float mps = ((freq * (0.3 / 24.15)) / 2.0) / cos((PI * angle) / 180);`

**Comment by hcs-svn** [comment]
Done

I have provided the variable "mountingAngle" that you can use in your calculations.
The help page now uses the defined angle for the speed calculation.

```
  // Get the measurement settings
  publishInterval = settings.GetUInt("PublishInterval", DEFAULT_PUBLISH_INTERVAL);
  detectionTreshold = settings.GetUInt("DetectionThreshold", DEFAULT_DETECTION_TRESHOLD);
  mountingAngle = settings.GetUInt("SMA", 45);
```
